port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
proxies:
- name: 香港07
  type: ss
  server: efan9863.dns8656815.com
  port: 8757
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 香港03
  type: ss
  server: efan9863.dns8656815.com
  port: 8753
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 香港18
  type: ss
  server: efan9863.dns8656815.com
  port: 8718
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 香港19
  type: ss
  server: efan9863.dns8656815.com
  port: 8719
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 香港14
  type: ss
  server: efan9863.dns8656815.com
  port: 8714
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 台湾01
  type: ss
  server: efan9863.dns8656815.com
  port: 8741
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 台湾02
  type: ss
  server: efan9863.dns8656815.com
  port: 8742
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 台湾03
  type: ss
  server: efan9863.dns8656815.com
  port: 8743
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 台湾04
  type: ss
  server: efan9863.dns8656815.com
  port: 8744
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 台湾05
  type: ss
  server: efan9863.dns8656815.com
  port: 8745
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 美国08
  type: ss
  server: efan9863.dns8656815.com
  port: 8778
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 美国02
  type: ss
  server: efan9863.dns8656815.com
  port: 8772
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 美国03
  type: ss
  server: efan9863.dns8656815.com
  port: 8773
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 美国07
  type: ss
  server: efan9863.dns8656815.com
  port: 8777
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 美国05
  type: ss
  server: efan9863.dns8656815.com
  port: 8775
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 日本07
  type: ss
  server: efan9863.dns8656815.com
  port: 8767
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 日本02
  type: ss
  server: efan9863.dns8656815.com
  port: 8762
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 日本03
  type: ss
  server: efan9863.dns8656815.com
  port: 8763
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 日本04
  type: ss
  server: efan9863.dns8656815.com
  port: 8764
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 新加坡03
  type: ss
  server: efan9863.dns8656815.com
  port: 8723
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 新加坡09
  type: ss
  server: efan9863.dns8656815.com
  port: 8729
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 澳大利亚01
  type: ss
  server: efan9863.dns8656815.com
  port: 8799
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 巴西02
  type: ss
  server: efan9863.dns8656815.com
  port: 8648
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 加拿大01
  type: ss
  server: efan9863.dns8656815.com
  port: 8781
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 加拿大02
  type: ss
  server: efan9863.dns8656815.com
  port: 8782
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 瑞士02
  type: ss
  server: efan9863.dns8656815.com
  port: 8732
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 捷克02
  type: ss
  server: efan9863.dns8656815.com
  port: 8616
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 德国02
  type: ss
  server: efan9863.dns8656815.com
  port: 8796
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 德国01
  type: ss
  server: efan9863.dns8656815.com
  port: 8794
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 西班牙01
  type: ss
  server: efan9863.dns8656815.com
  port: 8797
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 法国02
  type: ss
  server: efan9863.dns8656815.com
  port: 8784
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 法国01
  type: ss
  server: efan9863.dns8656815.com
  port: 8783
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 希腊01
  type: ss
  server: efan9863.dns8656815.com
  port: 8733
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 希腊02
  type: ss
  server: efan9863.dns8656815.com
  port: 8734
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 匈牙利02
  type: ss
  server: efan9863.dns8656815.com
  port: 8618
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 意大利02
  type: ss
  server: efan9863.dns8656815.com
  port: 8736
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 意大利01
  type: ss
  server: efan9863.dns8656815.com
  port: 8735
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 荷兰02
  type: ss
  server: efan9863.dns8656815.com
  port: 8793
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 波兰02
  type: ss
  server: efan9863.dns8656815.com
  port: 8632
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 葡萄牙01
  type: ss
  server: efan9863.dns8656815.com
  port: 8621
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 葡萄牙02
  type: ss
  server: efan9863.dns8656815.com
  port: 8622
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 俄罗斯01
  type: ss
  server: efan9863.dns8656815.com
  port: 8637
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 俄罗斯02
  type: ss
  server: efan9863.dns8656815.com
  port: 8638
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 土耳其02
  type: ss
  server: efan9863.dns8656815.com
  port: 8789
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 土耳其01
  type: ss
  server: efan9863.dns8656815.com
  port: 8788
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
- name: 英国02
  type: ss
  server: efan9863.dns8656815.com
  port: 8787
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202603200067130-cO3QGRDPup.download.microsoft.com
proxy-groups:
- name: 🌐 节点选择
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 香港07
  - 香港03
  - 香港18
  - 香港19
  - 香港14
  - 台湾01
  - 台湾02
  - 台湾03
  - 台湾04
  - 台湾05
  - 美国08
  - 美国02
  - 美国03
  - 美国07
  - 美国05
  - 日本07
  - 日本02
  - 日本03
  - 日本04
  - 新加坡03
  - 新加坡09
  - 澳大利亚01
  - 巴西02
  - 加拿大01
  - 加拿大02
  - 瑞士02
  - 捷克02
  - 德国02
  - 德国01
  - 西班牙01
  - 法国02
  - 法国01
  - 希腊01
  - 希腊02
  - 匈牙利02
  - 意大利02
  - 意大利01
  - 荷兰02
  - 波兰02
  - 葡萄牙01
  - 葡萄牙02
  - 俄罗斯01
  - 俄罗斯02
  - 土耳其02
  - 土耳其01
  - 英国02
rules:
- MATCH,🌐 节点选择
