port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
proxies:
- name: 香港01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8751
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 香港10
  type: ss
  server: cn01.efan8867801.xyz
  port: 8760
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 香港16
  type: ss
  server: cn01.efan8867801.xyz
  port: 8716
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 香港13
  type: ss
  server: cn01.efan8867801.xyz
  port: 8713
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 香港05
  type: ss
  server: cn01.efan8867801.xyz
  port: 8755
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 台湾05
  type: ss
  server: cn01.efan8867801.xyz
  port: 8745
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 台湾02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8742
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 台湾03
  type: ss
  server: cn01.efan8867801.xyz
  port: 8743
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 台湾04
  type: ss
  server: cn01.efan8867801.xyz
  port: 8744
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 台湾07
  type: ss
  server: cn01.efan8867801.xyz
  port: 8747
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 美国01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8771
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 美国08
  type: ss
  server: cn01.efan8867801.xyz
  port: 8778
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 美国03
  type: ss
  server: cn01.efan8867801.xyz
  port: 8773
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 美国04
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 美国05
  type: ss
  server: cn01.efan8867801.xyz
  port: 8775
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 日本03
  type: ss
  server: cn01.efan8867801.xyz
  port: 8763
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 日本05
  type: ss
  server: cn01.efan8867801.xyz
  port: 8765
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 日本01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8761
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 日本02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8762
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 日本07
  type: ss
  server: cn01.efan8867801.xyz
  port: 8767
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 日本04
  type: ss
  server: cn01.efan8867801.xyz
  port: 8764
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 日本06
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 新加坡03
  type: ss
  server: cn01.efan8867801.xyz
  port: 8723
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 新加坡01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8721
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 新加坡02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8722
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 澳大利亚02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8800
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 澳大利亚01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8799
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 巴西02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8648
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 巴西01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8647
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 加拿大02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8782
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 加拿大01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8781
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 瑞士02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8732
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 捷克01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8615
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 捷克02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8616
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 德国01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8794
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 西班牙01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8797
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 西班牙02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8798
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 法国01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8783
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 希腊02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8734
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 匈牙利01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8617
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 匈牙利02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8618
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 意大利01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8735
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 荷兰01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8791
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 波兰01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8631
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 葡萄牙01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8621
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 俄罗斯02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8638
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 土耳其01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8788
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 土耳其02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8789
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 英国02
  type: ss
  server: cn01.efan8867801.xyz
  port: 8787
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
- name: 英国01
  type: ss
  server: cn01.efan8867801.xyz
  port: 8786
  cipher: rc4-md5
  password: efanccyun
  plugin: obfs
  plugin-opts:
    mode: http
    host: 202503131222137-I1Qlb2V1Rh.download.microsoft.com
proxy-groups:
- name: 🌐 节点选择
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 香港01
  - 香港10
  - 香港16
  - 香港13
  - 香港05
  - 台湾05
  - 台湾02
  - 台湾03
  - 台湾04
  - 台湾07
  - 美国01
  - 美国08
  - 美国03
  - 美国04
  - 美国05
  - 日本03
  - 日本05
  - 日本01
  - 日本02
  - 日本07
  - 日本04
  - 日本06
  - 新加坡03
  - 新加坡01
  - 新加坡02
  - 澳大利亚02
  - 澳大利亚01
  - 巴西02
  - 巴西01
  - 加拿大02
  - 加拿大01
  - 瑞士02
  - 捷克01
  - 捷克02
  - 德国01
  - 西班牙01
  - 西班牙02
  - 法国01
  - 希腊02
  - 匈牙利01
  - 匈牙利02
  - 意大利01
  - 荷兰01
  - 波兰01
  - 葡萄牙01
  - 俄罗斯02
  - 土耳其01
  - 土耳其02
  - 英国02
  - 英国01
rules:
- MATCH,🌐 节点选择
