name: Auto Update Nodes

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch: # 允许你手动点击运行

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to update config.yaml
        run: python update.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config.yaml
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update nodes"
          git push
